apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-init
  namespace: equino-postgres
data:
  01_roles_access.sh: |
    #!/bin/bash
    cp /var/lib/postgresql/config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
  02_db_init.sh: |
    #!/bin/bash
    psql -c "ALTER ROLE ${POSTGRES_USERNAME} WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD '${POSTGRES_PASSWORD}';"

    psql -c "CREATE ROLE ${OWNER_USERNAME} WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 10 PASSWORD '${OWNER_PASSWORD}';"
    psql -c "CREATE ROLE ${APP_USERNAME} WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 10 PASSWORD '${APP_PASSWORD}';"

    psql -c "CREATE DATABASE ${DB_NAME} WITH OWNER ${OWNER_USERNAME};"
    psql ${DB_NAME} -c "CREATE SCHEMA IF NOT EXISTS ${SCHEMA_NAME} AUTHORIZATION ${OWNER_USERNAME};"

    psql ${DB_NAME} -c "GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO ${APP_USERNAME};"
    psql ${DB_NAME} -c "ALTER DEFAULT PRIVILEGES FOR USER ${OWNER_USERNAME} IN SCHEMA ${SCHEMA_NAME} GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USERNAME};"
