apiVersion: v1
kind: ConfigMap
metadata:
  name: actracker-api-config
  namespace: equino-int
data:
  SPRING_PROFILES_ACTIVE: int
  actracker-api.environment: int
  actracker-api-db-postgres.dbName: actracker_int
  actracker-api-db-postgres.schema: actracker_int_schema
  actracker-api-db-postgres.host: actracker-int.equino-postgres.svc.cluster.local
  actracker-api-db-postgres.port: "5432"
  actracker-api-publisher-rabbitmq.host: equino-cluster.equino-rabbitmq.svc.cluster.local
  actracker-api-publisher-rabbitmq.vhost: actracker-int
  actracker-api-publisher-rabbitmq.port: "5672"
