apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: equino-elastic
  name: equino-cluster
spec:
  version: 8.6.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false