apiVersion: v1
kind: Pod
metadata:
  namespace: equino
  labels:
    name: jenkins-agent-jdk17-dind
spec:
  serviceAccountName: jenkins-admin
  containers:
    - name: jdk
      image: openjdk:17-jdk
      resources:
        requests:
          cpu: "0.5"
          memory: "1800Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
      env:
        - name: DOCKER_HOST
          value: 'tcp://localhost:2375'
      imagePullPolicy: Always
      tty: true
      command: ["cat"]
    - name: dind
      image: docker:24.0.7-dind
      resources:
        limits:
          cpu: "0.2"
          memory: "250Mi"
      imagePullPolicy: Always
      tty: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true