apiVersion: v1
kind: Pod
metadata:
  namespace: equino
  labels:
    name: jenkins-agent-k8s
spec:
  serviceAccountName: jenkins-admin
  volumes:
    - name: "workspace-volume"
      persistentVolumeClaim:
        claimName: "jenkins-agent-k8s-pvc"
        readOnly: false
  containers:
    - name: jnlp
      resources:
        requests:
          cpu: "0.5"
          memory: "1800Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
      env:
        - name: "AGENT_WORKDIR"
          value: "/home/jenkins"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins"
        - name: DOCKER_HOST
          value: 'tcp://localhost:2375'
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
    - name: dind
      image: docker:24.0.7-dind
      resources:
        limits:
          cpu: "0.2"
          memory: "250Mi"
      imagePullPolicy: Always
      tty: true
      env:
        - name: "AGENT_WORKDIR"
          value: "/home/jenkins"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins"
        - name: DOCKER_TLS_CERTDIR
          value: ""
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
      securityContext:
        privileged: true
