apiVersion: v1
kind: Pod
metadata:
  namespace: equino
  labels:
    name: jenkins-agent-jdk17-dind
spec:
  serviceAccountName: jenkins-admin
  volumes:
    - name: "workspace-volume"
      persistentVolumeClaim:
        claimName: "jenkins-agent-pvc"
        readOnly: false
  containers:
#    - name: jnlp
#      image: jenkins/inbound-agent
#      resources:
#        limits:
#          cpu: "0.2"
#          memory: "250Mi"
#        imagePullPolicy: Always
#        tty: true
#        env:
    - name: jdk
      image: openjdk:17-jdk
      resources:
        requests:
          cpu: "0.2"
          memory: "700Mi"
        limits:
          cpu: "0.5"
          memory: "1G"
      imagePullPolicy: Always
      tty: true
      command: ["cat"]
    - name: dind
      image: docker:24.0.7-dind
      resources:
        limits:
          cpu: "0.2"
          memory: "250Mi"
      imagePullPolicy: Always
      tty: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true