apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: equino-docker-registry
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: equino-docker-registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:3.0.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: my-registry-localstorage-volume
              mountPath: /var/lib/registry
      volumes:
        - name: my-registry-localstorage-volume
          persistentVolumeClaim:
            claimName: registry-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: equino-docker-registry
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd, equino-docker-registry-registry-cors@kubernetescrd, equino-docker-registry-registry-basic-auth@kubernetescrd
spec:
  rules:
    - host: registry.cloud.equino.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 80
  tls:
    - secretName: registry-tls
      hosts:
        - registry.cloud.equino.ovh