apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: equino
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: registry-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: equino
spec:
  selector:
    matchLabels:
      app: registry-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:2.3.3
          ports:
            - containerPort: 80
          env:
            - name: SINGLE_REGISTRY
              value: "true"
            - name: REGISTRY_TITLE
              value: "Equino Docker Registry"
            - name: REGISTRY_URL
              value: "https://registry.cloud.equino.ovh"
            - name: NGINX_PROXY_PASS_URL
              value: "https://registry.cloud.equino.ovh"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ui-ingress
  namespace: equino
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
spec:
  rules:
    - host: registry-ui.cloud.equino.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-ui
                port:
                  number: 80
  tls:
    - secretName: registry-ui-tls
      hosts:
        - registry-ui.cloud.equino.ovh